[project]
path = "/Users/miethe/dev/homelab/development/CCDash"
name = "CCDash"
created_at = "2026-02-20T18:11:39.333363"
description = "Dashboard for Agentic Coding Sessions and Feature/Project Tracking."
